[build]
command = "npm run build"
publish = "build"

# Netlify defaults to Node v12.16. SvelteKit requires Node v12.20 to build.
[build.environment]
NODE_VERSION = "14.17.6"
NPM_VERSION = "7.23.0"
NODE_ENV = "development"
